# Generated by Django 6.1.1 on 2026-09-13 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de 3 letras, por ejemplo USD, EUR o PYG.', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}$', 'El código debe tener exactamente 3 letras (ISO 4217). Ej.: USD.')], verbose_name='código ISO 4217')),
                ('nombre', models.CharField(help_text='Nombre descriptivo. Ej.: Dólar Americano.', max_length=80, verbose_name='nombre')),
                ('simbolo', models.CharField(blank=True, help_text='Símbolo usado al mostrar montos. Ej.: $, €, Gs.', max_length=8, verbose_name='símbolo')),
                ('decimales', models.PositiveSmallIntegerField(default=2, help_text='Cantidad de decimales con la que se muestran los montos. El guaraní usa 0, la mayoría de las divisas usa 2.', validators=[django.core.validators.MaxValueValidator(8)], verbose_name='decimales')),
                ('pais_iso', models.CharField(blank=True, help_text='Código de 2 letras usado para mostrar la bandera. Ej.: US, PY.', max_length=2, verbose_name='código de país ISO 3166-1')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivada, la moneda no se ofrece a los clientes.', verbose_name='activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'ordering': ['codigo'],
            },
        ),
    ]
