# Generated by Django 6.1.1 on 2026-09-27 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_clientes_demo'),
        ('monedas', '0002_monedas_default'),
        ('pagos', '0002_metodos_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Nace en cero; se mueve al confirmar operaciones.', max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='saldo')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billeteras', to='clientes.cliente', verbose_name='cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billeteras', to='monedas.moneda', verbose_name='moneda')),
            ],
            options={
                'verbose_name': 'billetera',
                'verbose_name_plural': 'billeteras',
                'ordering': ['moneda__codigo'],
            },
        ),
        migrations.CreateModel(
            name='MedioAcreditacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BILLETERA', 'Billetera digital'), ('CUENTA', 'Cuenta bancaria')], max_length=10, verbose_name='tipo')),
                ('es_default', models.BooleanField(default=False, help_text='Se preselecciona al operar.', verbose_name='medio por defecto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('billetera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='billeteras.billetera', verbose_name='billetera')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_acreditacion', to='clientes.cliente', verbose_name='cliente')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='pagos.cuentabancaria', verbose_name='cuenta bancaria')),
            ],
            options={
                'verbose_name': 'medio de acreditación',
                'verbose_name_plural': 'medios de acreditación',
                'ordering': ['-es_default', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billetera',
            constraint=models.UniqueConstraint(fields=('cliente', 'moneda'), name='uniq_billetera_cliente_moneda'),
        ),
    ]
