# Generated by Django 6.1.1 on 2026-09-27 20:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeteras', '0001_initial'),
        ('operaciones', '0004_operacion_billetera_destino_operacion_cuenta_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto acreditado')),
                ('saldo_resultante', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='saldo resultante')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='billeteras.billetera', verbose_name='billetera')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='operaciones.operacion', verbose_name='operación')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
