# Generated by Django 6.1.1 on 2026-09-27 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeteras', '0002_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], default='CREDITO', max_length=8, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto del movimiento'),
        ),
    ]
