# Generated by Django 6.1.1 on 2026-09-13 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre / razón social')),
                ('documento', models.CharField(max_length=32, unique=True, verbose_name='documento / RUC')),
                ('email', models.EmailField(max_length=160, verbose_name='correo electrónico')),
                ('tipo', models.CharField(choices=[('FISICA', 'Persona física'), ('JURIDICA', 'Persona jurídica')], default='FISICA', max_length=10, verbose_name='tipo de cliente')),
                ('categoria', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=12, verbose_name='categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], max_length=12, unique=True, verbose_name='categoría')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej.: 1.00 = 1%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje (%)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'comisión por categoría',
                'verbose_name_plural': 'comisiones por categoría',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(help_text='Claim "sub" del access token del usuario.', max_length=64, verbose_name='sub de Keycloak')),
                ('username', models.CharField(blank=True, max_length=160, verbose_name='usuario')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'asociación usuario-cliente',
                'verbose_name_plural': 'asociaciones usuario-cliente',
                'ordering': ['cliente__nombre', 'username'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'keycloak_id'), name='uniq_cliente_usuario')],
            },
        ),
    ]
