# Generated by Django 6.1.1 on 2026-09-13 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.DecimalField(decimal_places=2, help_text='Guaraníes que la casa paga por 1 unidad.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio de compra')),
                ('venta', models.DecimalField(decimal_places=2, help_text='Guaraníes que el cliente paga por 1 unidad.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio de venta')),
                ('vigente_desde', models.DateTimeField(auto_now_add=True, help_text='Marca temporal de la cotización (RNF25).', verbose_name='vigente desde')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario de Keycloak que registró la tasa (trazabilidad, RNF26).', max_length=160, verbose_name='creado por')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='monedas.moneda', verbose_name='moneda')),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-vigente_desde'],
            },
        ),
    ]
