# Generated by Django 6.1.1 on 2026-09-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador estable. Ej.: transfer, wallet, card, qr.', max_length=24, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado no se ofrece a los clientes.', verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'método de pago',
                'verbose_name_plural': 'métodos de pago',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='apellido')),
                ('cedula', models.CharField(max_length=32, verbose_name='nº cédula')),
                ('banco', models.CharField(max_length=120, verbose_name='entidad bancaria')),
                ('numero_cuenta', models.CharField(max_length=64, verbose_name='nº de cuenta bancaria')),
                ('codigo_bancario', models.CharField(max_length=32, verbose_name='código bancario')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clientes.cliente', verbose_name='cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='monedas.moneda', verbose_name='moneda')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['banco', 'numero_cuenta'],
            },
        ),
    ]
