# Generated by Django 6.1.1 on 2026-09-24 22:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_clientes_demo'),
        ('monedas', '0002_monedas_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_keycloak_id', models.CharField(help_text='Claim "sub" del access token que ejecutó la operación.', max_length=64, verbose_name='sub de Keycloak')),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6, verbose_name='tipo de operación')),
                ('monto_enviado', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto enviado (origen)')),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto recibido neto (destino)')),
                ('cotizacion_aplicada', models.DecimalField(decimal_places=6, help_text='Factor efectivo bruto (bruto_destino / monto_enviado_origen).', max_digits=18, verbose_name='tipo efectivo origen->destino')),
                ('tasa_origen', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa compra si origen es divisa; 1 si es PYG.', max_digits=14, null=True, verbose_name='tasa PYG de origen')),
                ('tasa_destino', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa venta si destino es divisa; 1 si es PYG.', max_digits=14, null=True, verbose_name='tasa PYG de destino')),
                ('porcentaje_comision_aplicado', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='comisión aplicada (%)')),
                ('monto_comision', models.DecimalField(decimal_places=2, help_text='Siempre expresada en moneda destino.', max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='comisión en moneda destino')),
                ('metodo_pago', models.CharField(blank=True, help_text='Informativo: transfer, wallet, card, qr.', max_length=24, verbose_name='método de pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='clientes.cliente', verbose_name='cliente')),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_destino', to='monedas.moneda', verbose_name='moneda destino')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_origen', to='monedas.moneda', verbose_name='moneda origen')),
            ],
            options={
                'verbose_name': 'operación',
                'verbose_name_plural': 'operaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
