# Generated by Django 6.1.1 on 2026-09-26 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='cancelada_por',
            field=models.CharField(blank=True, max_length=64, verbose_name='cancelada por (sub Keycloak)'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='cancelada_por_nombre',
            field=models.CharField(blank=True, max_length=160, verbose_name='cancelada por (usuario)'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelación'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='fecha_cotizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se fijaron las tasas; arranca la ventana de tolerancia.', verbose_name='cotización congelada en'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('COTIZACION_CAMBIADA', 'No aceptó la nueva cotización'), ('DESISTIO', 'El cliente desistió')], max_length=24, verbose_name='motivo de cancelación'),
        ),
    ]
