# Generated by Django 6.1.1 on 2026-09-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_operacion_cancelada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], db_index=True, default='PENDIENTE', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de confirmación de pago'),
        ),
    ]
