# Generated by Django 6.1.1 on 2026-09-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeteras', '0001_initial'),
        ('operaciones', '0003_alter_operacion_estado_and_more'),
        ('pagos', '0002_metodos_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='billetera_destino',
            field=models.ForeignKey(blank=True, help_text='Billetera donde se acreditarán los fondos al confirmar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_destino', to='billeteras.billetera', verbose_name='billetera destino'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='cuenta_origen',
            field=models.ForeignKey(blank=True, help_text='Cuenta desde donde salen los fondos al confirmar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_origen', to='pagos.cuentabancaria', verbose_name='cuenta origen'),
        ),
    ]
