# Generated by Django 6.1.1 on 2026-09-27 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billeteras', '0003_movimiento_tipo_alter_movimiento_monto'),
        ('operaciones', '0004_operacion_billetera_destino_operacion_cuenta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='billetera_origen',
            field=models.ForeignKey(blank=True, help_text='Billetera desde donde se descuenta al confirmar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_origen_billetera', to='billeteras.billetera', verbose_name='billetera origen'),
        ),
    ]
