# Generated by Django 6.1.1 on 2026-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_operacion_billetera_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('COTIZACION_CAMBIADA', 'No aceptó la nueva cotización'), ('DESISTIO', 'El cliente desistió'), ('FONDOS_INSUFICIENTES', 'Fondos insuficientes')], max_length=24, verbose_name='motivo de cancelación'),
        ),
    ]
